export const itineraries = {
    varanasi: {
      title: "Varanasi 1-Day Yatra Package",
      slug: "varanasi",
      imageUrl: "/images/itinerary/Varanasi_2.jpg",
      price: "₹3,999",
      description: "Experience the divine aura of Kashi Vishwanath and the mesmerizing Ganga Aarti.",
      highlights: [
        "🚗 Comfortable AC travel with an experienced driver for a hassle-free journey",
        "👵 Special care for elderly devotees, ensuring a smooth darshan experience",
        "🔄 Customizable itinerary—your yatra, your way!",
        "💰 Pay on arrival for a stress-free booking experience",
        "🌅 Witness the divine Ganga Aarti at the sacred Dashashwamedh Ghat",
      ],
      itinerary: [
        { time: "1:00 AM", activity: "🚗 Departure from Prayagraj – Early morning departure for a peaceful and hassle-free darshan." },
        { activity: "🛕 Kashi Vishwanath Temple Darshan – Seek blessings at one of the 12 Jyotirlingas." },
        { activity: "🌸 Annapurna Devi Temple Visit – Offer prayers to Goddess Annapurna." },
        { activity: "🙏 Vishalakshi Temple – A revered Shakti Peeth dedicated to Goddess Vishalakshi." },
        { activity: "⚔️ Kal Bhairav Temple Visit – Pay homage to Lord Kal Bhairav, the guardian deity of Varanasi." },
        { activity: "🍽️ Breakfast Break (Self-Paid) – Stop at a recommended restaurant." },
        { activity: "🚣 Boat Ride at Dashashwamedh Ghat – Experience the mystical beauty of the Ganges." },
        { activity: "🐵 Sankat Mochan Hanuman Temple Visit – Seek blessings from Lord Hanuman." },
        { activity: "🍛 Lunch Break (Self-Paid) – Enjoy a traditional vegetarian meal." },
        { activity: "🛍️ Free Time for Shopping & Exploration (If time permits)." },
        { activity: "🌅 Ganga Aarti at Dashashwamedh Ghat – Witness the spectacular evening aarti." },
        { activity: "🚗 Departure to Prayagraj – Drive back home with divine blessings." },
      ],
      notIncluded: [
        "❌ Pickup & drop services (Available on request)",
        "❌ Breakfast & lunch (Enjoy self-paid meals at our recommended restaurants)",
        "❌ Personal expenses & shopping",
      ],
    },
  
    ayodhya: {
      title: "Ayodhya 1-Day Yatra",
      slug: "ayodhya",
      imageUrl: "/images/itinerary/Ayodhya_2.jpg",
      price: "₹4,499",
      description: "A soulful journey to the birthplace of Lord Ram, filled with devotion and history.",
      highlights: [
        "🚗 Comfortable & stress-free travel – Just sit back, relax, and enjoy the divine vibes!",
        "👵 Special care for elderly devotees – Ensuring ease and comfort during the journey.",
        "🔄 Flexible & customizable itinerary – Want to add something special? Let us know!",
        "🛕 Hassle-free darshan – Skip long queues and experience a smooth darshan.",
        "💰 No advance payment – Pay on arrival and book with confidence.",
      ],
      itinerary: [
        { time: "1:00 AM", activity: "🚗 Departure from Prayagraj – Early morning journey to maximize your spiritual experience." },
        { activity: "🛕 Sacred Snan at Ram Ki Paidi – Take a holy dip in the Sarayu River to cleanse your soul." },
        { activity: "🙏 Hanuman Garhi Darshan – Seek blessings from Lord Hanuman before visiting Ram Janmabhoomi." },
        { activity: "🏛️ Ram Janmabhoomi Temple – Feel the divine presence at the birthplace of Lord Ram." },
        { activity: "🍽️ Breakfast Break (Self-Paid) – Enjoy a delicious meal at a local restaurant." },
        { activity: "🏠 Kanak Bhavan Visit – A stunning temple gifted to Goddess Sita as a wedding present." },
        { activity: "🏛️ Dashrath Mahal – Explore the royal palace of King Dashrath, where Lord Ram spent his childhood." },
        { activity: "🍛 Lunch Break (Self-Paid) – Savor a traditional vegetarian meal at a recommended eatery." },
        { activity: "🛍️ Free Time for Shopping & Exploration (If time permits)." },
        { activity: "🕯️ Sarayu Aarti in the Evening – Witness the peaceful evening aarti by the Sarayu River." },
        { activity: "🚗 Return to Prayagraj – Head back home carrying divine blessings." },
      ],
      notIncluded: [
        "❌ Pickup & drop services (Available on request)",
        "❌ Breakfast & lunch (Enjoy self-paid meals at our recommended restaurants)",
        "❌ Personal expenses & shopping",
      ],
    },
  };
  