export const poojaItineraries = {
  navgrahaShantiPath: {
    title: "Navgraha Shanti Path Pooja at Prayagraj – 1-Day Spiritual Experience ✨",
    slug: "navgraha-shanti-path",
    imageUrl: "/images/poojaItinerary/nav_grah_shanti_path_prayagraj.jpg",
    price: "Custom Pricing Based on Package",
    description:
      "A powerful Vedic ritual dedicated to the nine celestial planets (Navgraha) to neutralize malefic planetary effects and ensure prosperity, balance, and spiritual well-being.",
    highlights: [
      "✔ Performed by expert Vedic priests following authentic rituals.",
      "✔ Conducted at the sacred Triveni Sangam, maximizing spiritual benefits.",
      "✔ Helps in overcoming planetary doshas like Kaal Sarp Dosh, Pitra Dosh & Grah Dosh.",
      "✔ Brings peace, prosperity, and harmony in personal and professional life.",
      "✔ Reduces obstacles caused by unfavorable planetary positions.",
    ],
    itinerary: [
      { time: "📅 Day 1", activity: "🔹 Arrival & Check-in – Pick-up from Prayagraj Railway Station or Airport, followed by hotel check-in." },
      { activity: "📜 Sankalp (Vow-Taking Ceremony) – Devotee takes a sacred vow with the guidance of the Purohit before starting the pooja." },
      { activity: "🛕 Navgraha Abhishek – Ritualistic bathing of the Navgrahas with holy offerings:" },
      { activity: "   🔹 Gangajal, Milk, Honey, Curd, Ghee, and Panchamrit." },
      { activity: "   🔹 Bel Patra, Flowers, and special Navgraha grains." },
      { activity: "📿 Navgraha Mantra Jaap – Chanting of sacred Vedic hymns dedicated to each planet." },
      { activity: "🔥 Havan (Fire Ritual) – Offering oblations for planetary peace and blessings." },
      { activity: "🕯 Aarti & Prasadam Distribution – Concluding the ritual with divine blessings." },
      { time: "📌 Departure", activity: "Drop-off at Prayagraj Railway Station or Airport." },
    ],
    inclusions: [
      "✔ Pick-up & Drop-off – from Prayagraj Airport/Railway Station.",
      "✔ Comfortable hotel accommodation in Prayagraj for the ritual.",
      "✔ Assigned Purohit (Priest) to perform the entire pooja.",
      "✔ Basic Pooja Samagri provided – Flowers, Bel Patra, Panchamrit, Milk, and Gangajal.",
      "✔ Personalized Navgraha offerings & Vedic mantra chanting.",
      "✔ Aarti, Havan, & Prasadam Distribution.",
    ],
    notIncluded: [
      "❌ Travel costs to and from Prayagraj (can be arranged at an additional cost).",
      "❌ Personal expenses like food, shopping, or extra donations.",
      "❌ Gold/Silver offerings (optional add-ons available).",
      "❌ Any additional rituals beyond the booked package.",
    ],
    bookingPolicy: [
      "✔ Pick-up & Drop-off Service Available – From Prayagraj Airport/Railway Station.",
      "✔ 50% Advance Payment at the time of booking.",
      "✔ Remaining 50% Payment on Arrival before pooja begins.",
    ],
  },

  mahaMrityunjayaPooja: {
    title: "Maha Mrityunjaya Pooja at Prayagraj – 1-Day Spiritual Experience ✨",
    slug: "maha-mrityunjaya-pooja",
    imageUrl: "/images/poojaItinerary/Rudrabhishek at Triveni sangam_.jpg",
    price: "Custom Pricing Based on Chanting Cycles",
    description: "A sacred and powerful Vedic ritual dedicated to Lord Shiva, performed for health, longevity, and divine protection.",
    highlights: [
      "✔ Performed at the sacred Triveni Sangam, enhancing spiritual power.",
      "✔ Brings relief from severe health issues & life-threatening diseases.",
      "✔ Removes Kaal Sarp Dosh, Grah Dosh & planetary obstacles.",
      "✔ Grants longevity, peace, and spiritual well-being.",
      "✔ Conducted by highly experienced Purohits in a sacred setting.",
    ],
    itinerary: [
      { time: "📅 Day 1", activity: "🔹 Arrival & Check-in – Pick-up from Prayagraj Railway Station or Airport, followed by hotel check-in." },
      { activity: "📜 Sankalp (Vow-Taking Ceremony) – The devotee takes a vow with Purohit’s guidance before starting the pooja." },
      { activity: "🛕 Shivling Abhishek – Holy Bathing of the Shivling with Gangajal, Milk, Honey, Curd, Ghee, Panchamrit, and Bel Patra." },
      { activity: "📿 Maha Mrityunjaya Mantra Jaap – Based on the selected package:" },
      { activity: "   🔹 108 Jaap – For general well-being." },
      { activity: "   🔹 1,000 Jaap – For deep spiritual protection." },
      { activity: "   🔹 1,25,000 Jaap – Full-fledged Anushthan for ultimate divine grace." },
      { activity: "🔥 Havan (Fire Ritual) – Purification & divine blessings." },
      { activity: "🕯 Aarti & Prasadam Distribution." },
      { time: "📌 Departure", activity: "Drop-off at Prayagraj Railway Station or Airport." },
    ],
    inclusions: [
      "✔ Pick-up & Drop-off – from Prayagraj Airport/Railway Station.",
      "✔ Comfortable hotel accommodation in Prayagraj for the ritual.",
      "✔ Assigned Purohit (Priest) to perform the entire pooja.",
      "✔ Basic Pooja Samagri provided – Bel Patra, Panchamrit, Milk, Flowers, and Gangajal.",
      "✔ 108 to 1008 Maha Mrityunjaya Jaaps as per the selected package.",
      "✔ Aarti, Havan, & Prasadam Distribution.",
    ],
    notIncluded: [
      "❌ Travel costs to and from Prayagraj (can be arranged at an additional cost).",
      "❌ Personal expenses like food, shopping, or extra donations.",
      "❌ Gold/Silver offerings (optional add-ons available).",
      "❌ Any additional rituals beyond the booked package.",
    ],
    bookingPolicy: [
      "✔ Pick-up & Drop-off Service Available – From Prayagraj Airport/Railway Station.",
      "✔ 50% Advance Payment at the time of booking.",
      "✔ Remaining 50% Payment on Arrival before pooja begins.",
    ],
  },

rudrabhishekPooja: {
  title: "Rudrabhishek Pooja at Triveni Sangam – 1-Day Spiritual Experience ✨",
  slug: "rudrabhishek-pooja",
  imageUrl: "/images/poojaItinerary/Rudrabhishek at Triveni sangam_.jpg",
  price: "Custom Pricing Based on Rituals",
  description: "A sacred ritual dedicated to Lord Shiva, performed at the Triveni Sangam to remove doshas, attract prosperity, and grant spiritual purification.",
  highlights: [
    "✔ Removes Negative Energies & Doshas – Helps overcome planetary obstacles like Kaal Sarp Dosh & Grah Dosh.",
    "✔ Health & Longevity – The sacred Maha Mrityunjaya Jaap in this pooja is known to promote well-being.",
    "✔ Wealth & Success – Attracts financial stability and career growth through divine blessings.",
    "✔ Ancestral & Moksha Benefits – Performing it at Triveni Sangam helps in ancestral peace and salvation.",
  ],
  itinerary: [
    { time: "📅 Day 1", activity: "🔹 Arrival & Check-in – Welcome at our partnered hotel in Prayagraj, followed by a briefing on the significance of Triveni Sangam & Rudrabhishek Pooja." },
    { activity: "🛶 Holy Triveni Snan & Boat Ride – Sacred bath (Snan) at Triveni Sangam for purification and spiritual cleansing." },
    { activity: "📜 Sankalp (Vow-Taking) – The Purohit helps the devotee take a sacred vow." },
    { activity: "🛕 Shivling Abhishek with Gangajal, Milk, Honey, Curd, Ghee, Panchamrit, Bel Patra, and Flowers." },
    { activity: "📿 Vedic Chanting – Recitation of Rudram Chamakam & Maha Mrityunjaya Mantra." },
    { activity: "🕯 Aarti & Prasadam Distribution." },
    { time: "📌 Departure", activity: "Guided local temple visits (Bade Hanuman Ji, Akshayvat, etc.), followed by drop-off at Prayagraj Railway Station or Airport." },
  ],
  inclusions: [
    "✔ Comfortable hotel accommodation for the duration of the package.",
    "✔ Triveni Snan & Boat Ride for a sacred experience.",
    "✔ Dedicated Purohit (Priest) to conduct the pooja.",
    "✔ Pooja Samagri (Offerings) like flowers, Bel Patra, Panchamrit, and Rudraksha.",
    "✔ Sacred Shivling Abhishek with milk, honey, curd, ghee, and Gangajal.",
    "✔ Vedic Chanting & Aarti by experienced priests.",
    "✔ Prasadam distribution after the pooja.",
    "✔ Guidance for local temple visits.",
  ],
  notIncluded: [
    "❌ Personal expenses like additional food, drinks, or shopping.",
    "❌ Special offerings like gold/silver Bilva Patra (available at extra cost).",
    "❌ Travel expenses to and from Prayagraj (can be arranged on request).",
    "❌ Additional accommodations beyond the included package duration.",
    "❌ Any extra rituals requested at the temple beyond the booked package.",
  ],
  bookingPolicy: [
    "✔ 50% Advance Payment at the time of booking.",
    "✔ 50% Payment on Arrival before the pooja begins.",
    "✔ Online payment options available via UPI, Net Banking, Debit Cards.",
  ],
},
}